language: php
php:
  - 7.2
env:
  # You may want to update this to whatever the latest version is, or keep it
  # the same as your local machines. However, I have only tested it with 1.8.0+.
  # There should be a time in the future when this is not necessary - it is
  # explained in more detail below.
  DOCKER_COMPOSE_VERSION: 3.8

  before_install:
    # update is required to update the repositories to see the new packages for
    # Docker.
    - sudo ./stack install test

after_script:
  - bash <(curl -s https://codecov.io/bash)